/*This header is automatically generated from caffe prototxt format.
The variable names influence of majority of APIs in the C application
Do not modify this file*/
#include "caffe_proto_params.h"


/* Array of structure containing CNN parameters. Each structure represents 1 layer.		
The order of the layers follow this structure.*/

const CAFFE_LYR_PARAM_T cnn_param_table[NO_DEEP_LAYERS] = {
{.lyrType = CONV,
.K = 9,
.nOutMaps = 64,
.winSize = -1,
.stride = -1,
.poolType = UNSUPPORTED_POOL,
.actType = -1,
.nOutputs = -1,
},
{.lyrType = POOL,
.K = -1,
.nOutMaps = -1,
.winSize = 10,
.stride = 5,
.poolType = MAX_POOL,
.actType = -1,
.nOutputs = -1,
},
{.lyrType = CONV,
.K = 9,
.nOutMaps = 256,
.winSize = -1,
.stride = -1,
.poolType = UNSUPPORTED_POOL,
.actType = -1,
.nOutputs = -1,
},
{.lyrType = POOL,
.K = -1,
.nOutMaps = -1,
.winSize = 6,
.stride = 4,
.poolType = MAX_POOL,
.actType = -1,
.nOutputs = -1,
},
{.lyrType = INNER_PROD,
.K = -1,
.nOutMaps = -1,
.winSize = -1,
.stride = -1,
.poolType = UNSUPPORTED_POOL,
.actType = -1,
.nOutputs = 5000,
},
{.lyrType = ACT,
.K = -1,
.nOutMaps = -1,
.winSize = -1,
.stride = -1,
.poolType = UNSUPPORTED_POOL,
.actType = RELU,
.nOutputs = -1,
},
{.lyrType = INNER_PROD,
.K = -1,
.nOutMaps = -1,
.winSize = -1,
.stride = -1,
.poolType = UNSUPPORTED_POOL,
.actType = -1,
.nOutputs = 101,
},
{.lyrType = SOFTMAX,
.K = -1,
.nOutMaps = -1,
.winSize = -1,
.stride = -1,
.poolType = UNSUPPORTED_POOL,
.actType = -1,
.nOutputs = -1,
}
};

