MAKEFILE_TOP_DIR=$(shell pwd)
MXP_FRWK_SRC_DIR=./src
TEST_SRC_DIR=./test
MXP_FRWK_INC_DIR=$(shell pwd)/inc
CMACRO_DEFS= -DCNN_SIMULATOR -DUSE_MXP_SIM
SIM_DIR= sim
include sources.mk
include ./sim/vbx_sim.mk

