#define NUM_PES 16 // number of PEs in system
#define IMAGE_SIZE (36*36)
#define IMAGE_WIDTH 36
#define L1_KERNEL_WIDTH 5
#define L1_KERNEL_SIZE (5*5)
#define L2_KERNEL_WIDTH 5
#define L2_KERNEL_SIZE (5*5)
#define L3_KERNEL_WIDTH 5
#define L3_KERNEL_SIZE (5*5)
#define L1_MAX_MAPS_PER_ECORE 2
#define L2_MAX_MAPS_PER_ECORE 2
#define L3_MAX_MAPS_PER_ECORE 4
#define L1_MAP_SIZE (16*16)
#define L1_MAP_WIDTH 16
#define L2_MAP_SIZE (8*8)
#define L2_MAP_WIDTH 8
#define L3_MAP_SIZE (4*4)
#define L3_MAP_WIDTH 4
#define L1_MAPS 32
#define L2_MAPS 32 
#define L3_MAPS 64 
#define WINDOW_SIZE1 3
#define WINDOW_SIZE2 3
#define WINDOW_SIZE3 3
#define DOWN_FAC1 2
#define DOWN_FAC2 2
#define DOWN_FAC3 2
#define CONV_PAD 2

#define NUM_HIDDEN_NEURONS 64
#define NUM_OUTPUT_NEURONS 10
