/*This file is automatically generated. Do not modify.
This file contains images from below test dataset.
*/
#ifndef _MNIST_TEST_IMAGES_H_
#define _MNIST_TEST_IMAGES_H_
#include "stdint.h"

#define NO_TEST_IMAGES	(10)

#define TEST_IMAGE_CHANELS	(1)

#define TEST_IMAME_HEIGHT	(28)

#define TEST_IMAGE_WIDTH	(28)

extern const uint8_t mnist_image_data[NO_TEST_IMAGES][TEST_IMAGE_CHANELS * TEST_IMAME_HEIGHT * TEST_IMAGE_WIDTH];

extern const uint32_t mnist_image_labels[NO_TEST_IMAGES];

#endif //_MNIST_TEST_IMAGES_H_
