/*This file is automatically generated. Do not modify.
*/
#ifndef _LENET_CONV_GEMM_PARAMS_H_
#define _LENET_CONV_GEMM_PARAMS_H_
#include "stdint.h"

#define NO_GEMMS	(2)

extern const uint32_t lenet_A_height[NO_GEMMS];

extern const uint32_t lenet_A_width[NO_GEMMS];

extern const uint32_t lenet_B_width[NO_GEMMS];

#endif //_LENET_CONV_GEMM_PARAMS_H_
