/*This file is automatically generated. Do not modify.
This file contains matrix dimensions for different GEMM based convolution layers
*/
#include "lenet_conv_gemm_params.h"

#pragma DATA_SECTION(lenet_A_height, ".shared_ocm")
const uint32_t lenet_A_height[NO_GEMMS] = {
20, 50};

const uint32_t lenet_A_width[NO_GEMMS] = {
25, 500};

const uint32_t lenet_B_width[NO_GEMMS] = {
576, 64};

